#!/usr/bin/env ruby
# frozen_string_literal: true

require "./leaky_job"

INTERVAL = 5 # seconds

Signal.trap('INT') { exit }

puts "Sending jobs at #{INTERVAL} second intervals..."
loop do
  LeakyJob.perform_async
  sleep INTERVAL
end
